export const START_GAME = 'START_GAME';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_CURRENT_ALIEN_AND_FLEET = 'SET_CURRENT_ALIEN_AND_FLEET';
export const SET_INSTRUCTIONS = 'SET_INSTRUCTIONS';
export const UPDATE_ALIENS = 'UPDATE_ALIENS';
export const UPDATE_PLAYER_TECH = 'UPDATE_PLAYER_TECH';
export const ADVANCE_PHASE = 'ADVANCE_PHASE';
export const ADVANCE_STEP = 'ADVANCE_STEP';
